### ISSUE TITLE
Make simultanious put methods stable

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#101]
If contract method update some slice of structures in storage, then we should check if it is possible to have multiple transaction in one block changing the same slice. If so, then we should store list as a k:v pairs with some common prefix. See example in  https://github.com/nspcc-dev/neofs-contract/pull/100

## Reputation contract

- `reputation.Put`: multiple reputation of one peer will fail in a single block.
```go
	reputationValues := GetByID(id)
	reputationValues = append(reputationValues, value)

	rawValues := std.Serialize(reputationValues)

	storage.Put(ctx, id, rawValues)
```

## Container contract

- `container.PutCotnainerSize`: multiple estimations of one container will fail in a single block.
```gp
	key := estimationKey(epoch, cid)
	s := getContainerSizeEstimation(ctx, key, cid)

	s.estimations = append(s.estimations, estimation{
		from: pubKey,
		size: usedSize,
	})

	storage.Put(ctx, key, std.Serialize(s))
```

- `container.Put`: multiple containers from new owners will fail in a single block.
```go
	addOrAppend(ctx, ownersKey, owner)
``` 

- `container.Put`: multiple containers from one owner will fail in a single block.
```go
	addOrAppend(ctx, owner, id)
```

The same applies for `container.Delete`.

## NeoFS contract

- `neofs.InnerRingCandidateAdd`, `neofs.InnerRingCandidateRemove`: multiple invocations from different candidates will fail in a single block.
```go
	candidates := getNodes(ctx, candidatesKey)

	list, ok := addNode(candidates, c)
	if !ok {
		panic("irCandidateAdd: candidate already in the list")
	}

	common.SetSerialized(ctx, candidatesKey, list)
```

## NeoFSID contract
- `neofsid.AddKey`, `neofsid.RemoveKey`: multiple inovcation for the same owner will fail in a single block.
```go
	info := getUserInfo(ctx, owner)

addLoop:
	for i := 0; i < len(keys); i++ {
		pubKey := keys[i]
		info.Keys = append(info.Keys, pubKey)
	}

	common.SetSerialized(ctx, owner, info)
```

--- 

Some of these cases are quite critical and others are not. I propose to fix container contract issues for v0.95.2 release and then fix others later by this order:

0. Container contract
1. Reputation contract
2. NeoFSID contract
3. NeoFS contract

**Comment by cthulhu-rider** [comment]
Needed to be revised.

**Comment by fyrchik** [comment]
The problem in task is that calculated GAS for tx execution will differ if both tx use the same slice.

**Comment by alexvanin** [comment]
I missed one thing in all these fixes: https://github.com/nspcc-dev/neofs-contract/pull/166#discussion_r759043657

So we need to fix it in other contracts as well. Update contract storage only after `RemoveVotes()`. 

1. https://github.com/nspcc-dev/neofs-contract/blob/master/reputation/reputation_contract.go#L114-L125
2. https://github.com/nspcc-dev/neofs-contract/blob/f0868c89fd88abfbf4e9729c3db7d9dee0ca5c35/neofsid/neofsid_contract.go#L128-L141
3. https://github.com/nspcc-dev/neofs-contract/blob/f0868c89fd88abfbf4e9729c3db7d9dee0ca5c35/neofsid/neofsid_contract.go#L186-L199
