### ISSUE TITLE
User-friendly error message on unexisting container delete

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-contract#121]
When I delete container which doesn't exist, I get an error:

```
$ neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --wif L4WT9dLYQ3NhtPuW3su3rvSvZhsw4aGVC1miPp1ovZiv2g1Cw4Z2 container delete --cid 8cBwxUKtbhu4YinpnaRRWbPGPh8zL3fqtBCRRy3sj5xh --await
return code: 1. 
Output: rpc error: transport error: rpc error: code = Unknown desc = could not handle request: could not handle request: could not execute Delete request: could not invoke method (delete): chain/client: contract execution finished with state FAULT; exception: at instruction 4885 (PICKITEM): PICKITEM: invalid index
```
The error is that container not found, but the error message is hard to read. My proposal is to return user-friendly error message like
`container <CID> doesn't exists`.

**Comment by alexvanin** [comment]
@realloc proposed to not return error if container does not exist on `container delete`. So we can remove `panic("container does not exists")` there but still we need to investigate why `getOwnerByID` panics.
