### ISSUE TITLE
Support zone transfer in NNS contract

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-contract#125]
To implement zone transfer in [coredns](https://github.com/nspcc-dev/coredns) we need `nns contract` support it too.

At least we need:
* Appropriate [SOA records](https://en.wikipedia.org/wiki/SOA_record)

**Comment by alexvanin** [comment]
Blocked by https://github.com/nspcc-dev/neofs-contract/issues/123
