### ISSUE TITLE
Invoke `Init` with empty keys list

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-contract#16]
There is no check on Inner Ring keys list length in `Init` method. A person might invoke `Init` with empty list and "block" a smartcontract because they cannot invoke `Init` again and they cannot invoke `InnerRingUpdate` to update keys list due to approvers absence.

From the other hand, the contract would be invoked by a person who is qualified in what they do and for sure wouldn't shoot themself in a foot.

So my question is: is it necessary to check InnerRing keys list length in `Init` method?

**Comment by alexvanin** [comment]
While it is not necessary to check length of public key array or public key sizes, it can be a good feature for manual deploys. As practice shows, there are always human mistakes that can happen at initialization step. These checks are not expensive and they will be executed once.
