### ISSUE TITLE
netmap contract: improvement suggestions

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neofs-contract#169]
I took a glance at the `netmap_contract.go` and have several suggestions on how to improve the contract code:
* `_deploy` method may convert `data` to a struct with predefined fields instead of [iterating over `[]interface{}`](https://github.com/nspcc-dev/neofs-contract/blob/68eac87e64d69fe2cf2080032de375ff506c5e4b/netmap/netmap_contract.go#L64), i.e.:
```
	var input = data.(struct {
		notaryDisabled bool
		addrBalance   interop.Hash160
		addrContainer   interop.Hash160
                ...
	})
```  
* `UpdateState` method may use `interop.PublicKeyCompressedLen` [here](https://github.com/nspcc-dev/neofs-contract/blob/68eac87e64d69fe2cf2080032de375ff506c5e4b/netmap/netmap_contract.go#L254) instead of `33` constant. We also have other useful predefined constants inside `interop` package (`Hash160Len`, `Hash256Len`, etc.), I think it's a nice practice to use them in the situations like https://github.com/nspcc-dev/neofs-contract/blob/68eac87e64d69fe2cf2080032de375ff506c5e4b/netmap/netmap_contract.go#L87
* `ListConfig` method may convert `pair` to a struct with two fields inside ([here](https://github.com/nspcc-dev/neofs-contract/blob/68eac87e64d69fe2cf2080032de375ff506c5e4b/netmap/netmap_contract.go#L493)), i.e.
```
pair := iterator.Value(it).(struct {
		key []byte
		value []byte
	})
```
* `getNetmapNodes` method may use `storage.DeserializeValues` flag [here](https://github.com/nspcc-dev/neofs-contract/blob/68eac87e64d69fe2cf2080032de375ff506c5e4b/netmap/netmap_contract.go#L548) to omit subsequent call to `std.Deserialize`, i.e.:
```
	iter := storage.Find(ctx, candidatePrefix, storage.ValuesOnly|storage.DeserializeValues)
	for iterator.Next(iter) {
		n := iterator.Value(iter).(netmapNode)
		res = append(res, n)
	}
```

**Comment by carpawell** [comment]
@AnnaShaleva, 3rd suggestion did not work well with `panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident`

not sure is it ok or I made mistake somewhere

**Comment by AnnaShaleva** [comment]
> @AnnaShaleva, 3rd suggestion did not work well with `panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident` (tried to compile contracts)
> 

Could you try to extract iterator.Value firstly, and after that cast it to a struct (in a separate expression). Though, it's likely to be a compiler issue, @fyrchik, could you take a look, please?

**Comment by carpawell** [comment]
> Could you try to cast it to a struct in a separate expression?

yes, did not work either
