### ISSUE TITLE
Mark all NeoFS version-dependent places in code

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#178]
## Context

There are places of code that do not support the extensibility of the neofs protocol. Example: https://github.com/nspcc-dev/neofs-contract/blob/870db4a81a3298db530e46caf9d1b60faa2b7b55/subnet/subnet_contract.go#L43
They allow to optimize current contract on the one hand, and on the other hand - does not support NeoFS protocol extensions. Latter we can fix via `Update`, but there is no easy way to find where and what exactly needs to be changed when extending the protocol.

## Task
We need to mark all non-extensible places in contracts with common pattern. Example: TBD.

**Comment by carpawell** [comment]
`// V2 format check` template was used in the subnetwork contract
