### ISSUE TITLE
Enable `-` in domains

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#180]
NNS is being used for container aliasing. NNS contract restricts domains with `-` symbol. However `-` can be included in S3 bucket names, which are mapped to container name as well. Maybe it will be nice to enable it.

/cc @realloc @fyrchik @KirillovDenis

**Comment by realloc** [comment]
I suggest following regular DNS domain and S3 bucket naming rules here.

**Comment by alexvanin** [comment]
> I suggest following regular DNS domain and S3 bucket naming rules here.

According to [docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) S3 buckets may use `.` in the name. This becomes a bit tricky, because `.` is being used as a domain separator in NNS.

**Comment by realloc** [comment]
Suppose we have `some.bucket.name.s3` as a record in `s3` zone. Why should it cause problems?

**Comment by alexvanin** [comment]
> Suppose we have `some.bucket.name.s3` as a record in `s3` zone. Why should it cause problems?

No problem, you are right. For some reason I thought container contract registers new domain in `s3` zone. Instead it sets up a record, so it should be fine.
