### ISSUE TITLE
Check return value of token transfer

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#188]
I've noticed an issue: `alphabet_contract.go` (and probably other contracts) has `neo.Transfer` and `gas.Transfer` calls. These calls return boolean value whether the transfer was OK. You don't handle this value, it's dangerous.

_Originally posted by @AnnaShaleva in https://github.com/nspcc-dev/neofs-contract/pull/185#pullrequestreview-818660980_

**Comment by alexvanin** [comment]
There are only 3 places where we ignore return value:
1. Alphabet contract transfers NEO to itself to produce GAS,
2. Alphabet contract transfers GAS to proxy contract,
3. Alphabet contract transfers GAS to alphabet nodes.

I think it makes sense to check return value only in (1) case. If Alphabet contract can't produce GAS to spend, then it is okay to abort and panic.

But for (2) and (3) I don't think it is worth to do it. If there are some transfer issues (which should never happen, because receivers are not contracts, they are regular wallets, I hope :smiley: ) we should not abort but continue GAS emission for other nodes. We can log the failure, but I doubt anyone will see those logs. Maybe produce notification, but idk.

**Comment by AnnaShaleva** [comment]
> If there are some transfer issues (which should never happen, because receivers are not contracts, they are regular wallets, I hope)

Transfer can return false not only because of bad receiver, but also when you don't have enough funds to transfer or in case of bad witness or even if token fails to persist storage item changes, so there are various errors that could happen.

I paid attention to this issue in order to ensure it was done intentionally and you're aware of the consequences. If so, then we can keep the old code and omit `Transfer` result checking.

**Comment by AnnaShaleva** [comment]
I reviewed carefully usages of transfer, and I think that at least it's worth to add logs if something goes wrong with transfer. It will help to investigate issues.

For case (2) we have the following code:
```
		gas.Transfer(contractHash, proxyAddr, proxyGas, nil)
		gasBalance -= proxyGas
```
So here you always assume that transfer succeded and this affects `gasBalance` variable. This GAS then should be transferred to the storage nodes, so in the bad case when transfer (2) fails some GAS will still be available on the alphabet contract account, is it OK?

**Comment by alexvanin** [comment]
> it's worth to add logs if something goes wrong with transfer.

I am okay with logs, let's do that.

> at least proxyGas amount of GAS will still be available on the alphabet contract account, is it OK?

It is. We have a ratio of GAS emission between nodes and proxy contract. It will be more consistent to keep ratio even if some transfers have failed. In next emission, unspent GAS will be reused according to the ration.
