### ISSUE TITLE
Invalid usage of `storage.RemovePrefix`

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#191]
It should not work correctly in `neofs` contract because `storage.RemovePrefix` is used with `candidatesKey` which is a slice of bytes, not the single byte prefix.

**Comment by carpawell** [comment]
Usage is valid, `storage.Find` deletes the whole prefix if is used with `RemovePrefix`. Flag description is outdated in `neo-go` repo. Is fixed in https://github.com/nspcc-dev/neo-go/pull/2300.
