### ISSUE TITLE
Replace `common.IRNode` with `interop.PublicKey`

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-contract#222]
This is a structure with a single field, we can save on contract size and runtime GAS cost if we use `interop.PublicKey` directly.

**Comment by alexvanin** [comment]
Let's not change public interface of `AlphabetList()` and `InnerRingCandidates()` methods in `neofs` contract.
In `netmap` contract there is `InnerRingList()` method but it should be removed as soon as notary subsystem will be enabled in the side chain.
