### ISSUE TITLE
IR is not able to remove SN from netmap

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-contract#225]
After #162 it is impossible to make netmap cleanup by IR in notary-enabled mode: such `UpdateState` calls must be signed [both](https://github.com/nspcc-dev/neofs-contract/blob/v0.14.2/netmap/netmap_contract.go#L302) by a node and by the Alphabet.

IR still could process SN's requests to be removed but could not delete nodes that have not sent such requests (e.g. suddenly stopped): `netmap/process_cleanup.go:36 can't invoke netmap.UpdateState {"error": "could not invoke smart contract: chain/client: contract execution finished with state FAULT; exception: at instruction 1501 (THROW): unhandled exception: \"witness check failed\""} `

#### Possible solution:
1. Make two separate methods: for SN and for IR,
2. ...

**Comment by alexvanin** [comment]
Seems similar to in https://github.com/nspcc-dev/neofs-contract/issues/154#issuecomment-970341435. We chose an option to split adding peer into two methods: one (`AddPeer`) with storage node witness check, another (`Register`) with alphabet multisig witness check.

I think we have to do the same thing there, split `UpdateState` into `UpdateState` with storage node witness check and `???` with alphabet multisig witness check.
