### ISSUE TITLE
Add network config's keys constants

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-contract#241]
If I am not wrong the only way to find out what exactly key is used for some network configuration is [looking](https://github.com/nspcc-dev/neofs-node/blob/v0.28.0-rc.3/pkg/morph/client/netmap/config.go#L13-L22) at Go implementation of the NeoFS node.

IMO there should be some source of truth in some "canonical" repo: 
1. that repo;
2. SDK (but it looks like SDK should have Morph client then);
3. Spec (think it can share those constants anyway);
4. ...

**Comment by alexvanin** [comment]
As for me, it is more of API / SDK thing, because contracts do not use these constants at all. However I don't mind having network parameters definition there.

**Comment by carpawell** [comment]
@cthulhu-rider, @fyrchik what are your preferences?

**Comment by cthulhu-rider** [comment]
Such constants definitely must be defined in NeoFS SDK Go. Should contract modules import it? I don't think so: contracts are pretty version-dependent currently, and, regarding constants, they are version dependent, too.

**Comment by fyrchik** [comment]
If it isn't used in the contract, then it should be defined in the SDK. The only exceptions are fees for registering a container, which are used by the container contract directly.

**Comment by carpawell** [comment]
> defined in NeoFS SDK Go

> contracts are pretty version-dependent

@cthulhu-rider, how version dependency of the constants will live in the SDK repo?

**Comment by cthulhu-rider** [comment]
@carpawell SDK operates with constants in methods of the multi-version types.

**Comment by roman-khimov** [comment]
Obsoleted by https://github.com/nspcc-dev/neofs-contract/issues/314#issuecomment-1407044767.
