### ISSUE TITLE
Subnet `Delete` method is not verified by the Alphabet

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-contract#244]
### Context

In https://github.com/nspcc-dev/neofs-node/pull/1224 I synced contract's [`Delete`](https://github.com/nspcc-dev/neofs-contract/blob/f1f2101dc6a38a8c2cc29be4af6e167c9a780885/subnet/subnet_contract.go#L149) method and its handling by the Alphabet: TX is not required to be signed by the Alphabet and, therefore, it is not signed by the Alphabet now; the Alphabet only [handles](https://github.com/nspcc-dev/neofs-node/blob/786c920fb2c8afa2504084b5dbed39eb4c28f914/pkg/innerring/subnet.go#L292) netmap changes after the removal fact. Also, there is no such term as "notary `Delete` event" in the node repo: it does not exist because of the said above.

### Thoughts

However, thinking about it one more time after the merging led me to believe that something was wrong in the contract not in the IR code. IR is able to verify the removal TX (e.g. [do not remove](https://github.com/nspcc-dev/neofs-node/blob/786c920fb2c8afa2504084b5dbed39eb4c28f914/pkg/innerring/processors/subnet/delete.go#L37) zero subnet, it is impossible but anyway; also we may add more handling rules in the future) but it is the useless process: any subnet owner is able to remove its subnet without an Alphabet approval, the Alphabet only could [do something](https://github.com/nspcc-dev/neofs-contract/blob/f1f2101dc6a38a8c2cc29be4af6e167c9a780885/subnet/subnet_contract.go#L182) after the transaction is persisted on-chain.

### Solution if thoughts are accepted

- Add the voting process like it is already [done](https://github.com/nspcc-dev/neofs-contract/blob/f1f2101dc6a38a8c2cc29be4af6e167c9a780885/subnet/subnet_contract.go#L102-L125) for the `Put` method to `Delete` method
- Add `ParseDeleteNotary` method to the IR's subnet processor, the same way as it is [done](https://github.com/nspcc-dev/neofs-node/blob/786c920fb2c8afa2504084b5dbed39eb4c28f914/pkg/morph/event/subnet/put.go#L110) for the `Put`
- Adopt changes in `neofs-adm` (it should send appropriate TX with (non)notary support)

**Comment by cthulhu-rider** [comment]
We've decided with @carpawell @realloc @fyrchik to perform simple sanity checks on contract side and rid Inner Ring of these checks.

**Comment by carpawell** [comment]
> perform simple sanity checks on contract side

**Comment by carpawell** [comment]
> perform simple sanity checks on contract side

I figured out that we use proto marshaled [SubnetID](https://github.com/nspcc-dev/neofs-api/blob/master/refs/types.proto#L85) as the raw subnetID for contracts (dunno either it is a bug or feature) so that makes current [check](https://github.com/nspcc-dev/neofs-contract/blob/master/subnet/subnet_contract.go#L151) enough for restricting zero subnet removal (the true zero subnetID is zero length).
