### ISSUE TITLE
Update audit contract with new audit result structure

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#27]
Now audit contract won't transfer payments and should provide interface to store and get [audit result structures](https://github.com/nspcc-dev/neofs-api/issues/109). 

Stable marshaled audit result structures should be stored directly in contract storage and be accessible by the key. The key is a concatenation of epoch number, container ID and inner ring key. 

Extra 1: contract can add some prefix to the key, so it will be able to iterate over results by using such prefix. 
Extra 2: we group results by using prefixes of `epoch number` or `epoch number + container ID`.

**Comment by realloc** [comment]
Related: nspcc-dev/neofs-api#109

**Comment by alexvanin** [comment]
What should we return on listing operations? Right now in #28 listing functions return binary encoded audit results. But, I suppose, we can hit some output limits if there will be a lot of big audit results. 

We can return list of audit result IDs, however there is a small note: we do not store IDs as keys in contract memory (IDs are too big). However we can fetch the value (binary encoded audit result), get key from the value and put it in the result of the listing.

/cc @realloc

**Comment by realloc** [comment]
Let us have `List*` methods returning the list of IDs in a shortened format and `Get()` method accepting ID as argument.
