### ISSUE TITLE
Document contracts' storage model

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#275]
The memory of contracts has a structural organization, which can change during the update process. When changing the memory model, it is required to write a migration data routine from the previous model. To do this, I propose to document the organization of memory for developers in contracts. It is proposed to start with `Netmap` contract.

**Comment by cthulhu-rider** [comment]
* I'm gonna draft the proposal within #273

**Comment by fyrchik** [comment]
See also https://github.com/nspcc-dev/neo-go/issues/2561

**Comment by cthulhu-rider** [comment]
In demand in the context of updates. Lets do this for other contracts.

**Comment by roman-khimov** [comment]
Closing this one, because #320 was merged quite some time ago. The only thing left is NNS, that'd be #362.
