### ISSUE TITLE
Add contract update tests

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-contract#281]
Contract update is hard to test because we need to create the data using the old contracts and check it using the new ones. At the same time if anything goes wrong here, all NeoFS could stop working and bugfix can be really hard.

I propose to implement something like this:
1. Add a dump with dirty contract state. It should contain each contract with some dirty data.
2. Add a test which calls update method for each contract in turn and tries to read the data that was there before the deployment.
3. After each change in `common/version.go` create a new dump for the current "old" version.

**Comment by roman-khimov** [comment]
Fixed by Now #324.
