### ISSUE TITLE
`cli` artefact is left after almost all the `make` commands

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-contract#285]
Every build `make` command requires a `neo-go` binary. It is solved by [installing](https://github.com/nspcc-dev/neofs-contract/blob/6398b16a531d5f1bc128bfc0c98befea479230d3/Makefile#L38-L40) it as a `cli` global binary. IMO, it confuses and is not expected when building contracts, especially if none of the "clean" commands removes it.

Ideas:
1. Install/download `neo-go` locally in the repo dir.
2. Do not install `neo-go` if it is already installed.
3. Install `neo-go` anyway, but with proper naming and functionality (the current `cli` does not know what it is and what version it has).
4. ...

@cthulhu-rider, @fyrchik, @acid-ant

**Comment by alexvanin** [comment]
I am thinking about going with (3) for internal contract repos (`go get` and then `mv`). But I would like to adopt the same mechanism across all projects.
