### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-contract#287]
- Add some doc file that contains info about what exactly should be done before a release;
- (Optional) add some script(s) that prepares release files like it is already [done](https://github.com/nspcc-dev/neofs-node/blob/f76516a88347ab63d1b3e6732f9345be11dda405/Makefile#L43-L50) for the node repo.

**Comment by fyrchik** [comment]
https://github.com/nspcc-dev/neofs-contract/issues/281

**Comment by roman-khimov** [comment]
Fixed in #378, obsolete.
