### ISSUE TITLE
Implement re-usable contract clients

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-contract#292]
In neofs-node we have [clients](https://github.com/nspcc-dev/neofs-node/tree/master/pkg/morph) for interactions with neoFS smart contracts. These clients are currently used by storage node only.

However, it would be convenient to have these clients available in this repository so that they can be easily leveraged by other components.

**Comment by alexvanin** [comment]
Related to https://github.com/nspcc-dev/neofs-node/issues/621

**Comment by roman-khimov** [comment]
Obsolete, we have wrappers since 0.18.0 release.
