### ISSUE TITLE
Implement method to iterate over estimated container sizes

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-contract#293]
To process all container size estimates on epoch we are using combination of 2 methods of container smart contract:
* [ListContainerSizes](https://github.com/nspcc-dev/neofs-contract/blob/support/v0.16/container/container_contract.go#L555)
* [GetContainerSize](https://github.com/nspcc-dev/neofs-contract/blob/support/v0.16/container/container_contract.go#L541)

However, when there are many containers in the system, this method doesn't work efficiently. It takes about 3-4 seconds to process estimates of ~500 containers. To speed up processing on a system with multiple containers we want to implement an alternative method that would have signature:
```
func IterateContainerSizes(epoch int) iterator.Iterator { }
```

**Comment by roman-khimov** [comment]
Fixed by #295.
