### ISSUE TITLE
netmap contract limits the network to less than 700 nodes

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-contract#297]
We've got
```
func Netmap() []Node
```
and a number of similar APIs where a `Node` is a
```
type NodeState int
type Node struct {
        BLOB []byte
        State NodeState
}
```
`Netmap()` returns all of its data on the stack in an array of `Node` structures. Each `Node` takes three items in the VM to be represented (two elements, one container). We can only have 2048 items on the VM stack. Therefore we can't have more than 682 nodes on the network.

Granted, it's a pretty big number for installations we have today, but it doesn't look too big for some real applications with a lot of data and a lot of redundancy. So we better fix this before hitting this limit in production.

The other potential problem btw, is that the netmap is stored in a single value. I don't know how big a BLOB typically is, but given that it has a key, addresses and (potentially) some attributes, I'd estimate that to be ~50 bytes (some small array serialization overhead is also relevant here), so for a 64K value this means a limit of ~1310 elements.

**Comment by roman-khimov** [comment]
> 682 nodes

Or a half of that number because it'll break earlier that `Netmap()` call could occur. `filterNetmap` holds two copies of node list during the process.

**Comment by AnnaShaleva** [comment]
Just for the record, this problem is relevant for the `Snapshot` method used by the other contracts as far.

**Comment by roman-khimov** [comment]
The latest calculation is about 338 here given 7+4+4 items in slots and ~5 on the stack. But the problem would be severe, leading to inability to tick the epoch (`NewEpoch()` invocation failure).
