### ISSUE TITLE
Improve contract update and migration

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-contract#301]
Currently when updating from a very old version, we must update contracts multiple times, because we only support migration from a previous version. There were 2 reasons:
1. Avoid complex logic in contracts. We have only 1 "old" format and must migrate it to a single "new" format.
2. Easier testing (linear amount of user scenarios to test 1-2 + 2-3 + 3-4 vs possible 1-2,2-3,3-4 + 1-3,3-4 + 1-4 + 1-2,2-4 + something we will surely forget).

As @roman-khimov noticed this is not very user-friendly. One of the ways do fix this is to have  linear migration logic in the `_deploy` itself: we still migrate in a linear fashion, but can do it multiple times in a single update. This way we need to add a single migration when changing storage format, but also allow updating from old contract versions. Not to blow up contract size (neofs-adm would like to update contracts in a single transaction) we can also disallow updating from "very old" versions.

However, I would implement #281 first.

**Comment by roman-khimov** [comment]
I doubt contract size is much of a problem for us, we can have this logic in `_deploy` for quite some time. Eventually (depending on support cycles mostly) of course old transition code can be dropped with notices that version X.Y.Z can be upgraded to only from A.B.C or newer.

**Comment by roman-khimov** [comment]
> neofs-adm would like to update contracts in a single transaction

It does something like three of them already and this can be changed if needed, I think.

**Comment by roman-khimov** [comment]
#324 has implemented the new convention, effectively.
