### ISSUE TITLE
Define types for notification events and add converters from stack items

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#305]
* original proposal was roughly mentioned in https://github.com/nspcc-dev/neofs-node/pull/2211.

## Proposal
Define types for payloads of notifications thrown by smart contracts, e.g.:
```
type ContainerCreationRequest struct {
	Container    []byte
	Signature    []byte
	PublicKey    []byte
	SessionToken []byte
}
```
This will allow to import these types to application code (like NeoFS Inner Ring or NeoFS Storage node).

Provide payload decoders from stack like:
```
func (*ContainerCreationRequest) FromStack(items []stackitem.Item) error
```
The use of such functions will free applications using Neo Go from implementing and maintaining the relevance of converters.

**Comment by roman-khimov** [comment]
We have similar types in nep11/nep17/neo and other packages, but this should be a part of the `generate-rpcwrapper` command (manifests have this data). The other thing completely missing right now (even for defined types) is conversion function.

Ideally we'd have all of this handled by `generate-rpcwrapper` and have these wrappers stored in this repository (just like any other autogenerated code for protobufs/grpc) as reusable packages.

**Comment by roman-khimov** [comment]
RPC wrappers have them now. For example, https://pkg.go.dev/github.com/nspcc-dev/neofs-contract@v0.19.1/rpc/container#PutSuccessEvent
