### ISSUE TITLE
Refactor notifications emitted by balance contract

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neofs-contract#318]
Notifications `Mint` and `Burn` can be removed from the contract code as there's no users of it and (if needed) minting\burning can easily be tracked from the `Transfer` notifications with nil sender\receiver correspondingly.

Ref. #304.

**Comment by roman-khimov** [comment]
Are they used right now by any node code?

**Comment by AnnaShaleva** [comment]
> there's no users of it

I didn't find the users in the neofs-node, so I think these notifications are completely unused now.
