### ISSUE TITLE
Squash Transfer and TransferX methods of balance contract

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neofs-contract#319]
After notary-disabled mode will be removed from the contracts (https://github.com/nspcc-dev/neofs-contract/issues/303) we can safely remove `TransferX` method moving its functionality to the `Transfer` method. The functionality itself differs from simple `Transfer` in two ways:
 1) `TansferX` must be witnessed by alphabet multisig.
 2) Transfer details must be provided (can be handled via transfer `data` parameter).

This allows us to simplify contract's interface a bit.

Ref. #304.

**Comment by roman-khimov** [comment]
But we need it to be NEP-17, aren't we?

**Comment by AnnaShaleva** [comment]
Yes, and I don't see the problem here. We'll keep single `Transfer` method with four parameters. Could you clarify the issue?

**Comment by roman-khimov** [comment]
I'll be incompatible with NEP-17, so any NEP-17 things we have (like transfer tracking) won't work for it.

**Comment by AnnaShaleva** [comment]
Oh, you're right, we can't do this.
