### ISSUE TITLE
Do not store unused values in the contract storage 

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#322]
I've noticed that sometimes contracts store unused elements.

Example: https://github.com/nspcc-dev/neofs-contract/blob/5b007f429fa980ccd3879e328010aa771692e320/neofsid/neofsid_contract.go#L25

is just
https://github.com/nspcc-dev/neofs-contract/blob/5b007f429fa980ccd3879e328010aa771692e320/neofsid/neofsid_contract.go#L51

I suggest to catch all such places and stop saving on deploy. Optionally we can drop them on update.

**Comment by roman-khimov** [comment]
I think this was solved in 0.19.0, thus obsolete.
