### ISSUE TITLE
Get contract hashes from NNS during setup

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-contract#325]
We have a number of contracts and they use each other for various purposes, so many of them have `_deploy` parameters to specify hashes of other contracts. These parameters are not very useful and making deployment/upgrades more complicated then they need to be since we always have NNS in sidechain and it always has proper hashes of the target contracts.

**Comment by cthulhu-rider** [comment]
I'm a bit confused of next deployment parameters:
* `Container` contract depends on `Netmap` contract address https://github.com/nspcc-dev/neofs-contract/blob/715425a0a7e030ec1e0e32157701258dd77d47d9/container/container_contract.go#L146
* `Netmap` contract depends on `Container` contract address https://github.com/nspcc-dev/neofs-contract/blob/715425a0a7e030ec1e0e32157701258dd77d47d9/netmap/netmap_contract.go#L99

Will there be a conflict during deployment, or it is assumed that the hashes are known in advance (in the current topic - registered in the NNS)?

**Comment by roman-khimov** [comment]
The first one is only used during `cleanup` and can be reworked to not do so, #327.
