### ISSUE TITLE
Migration tests are missing something

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-contract#332]
We've got a number of `YmFsbG90cw==` ("ballots") storage entries in `mainnet-3309907-storage.csv` which means that migration should fail like this:
```
Error: deploy contract: script failed (FAULT state) due to an error: at instruction 71 (SYSCALL): failed native call: at instruction 807 (THROW): unhandled exception: "pending vote detected"
```
However this doesn't happen in migration tests.

**Comment by cthulhu-rider** [comment]
> However this doesn't happen in migration tests.

what do u expect? Test checks that with existing ballots `pending vote detected` panic occurs. If this panic  - test OK, otherwise FAIL

https://github.com/nspcc-dev/neofs-contract/blob/8df64fe444f802b539ff6174cc1ecc4c2e177000/container/migration_test.go#L95-L98

I changes check to `CheckUpdateSuccess` and 
```
--- FAIL: TestMigration (0.18s)
=== RUN   TestMigration/mainnet-3309907/container
    basic.go:213: 
...
        	Error:      	Not equal: 
        	            	expected: 0x1
        	            	actual  : 0x2
        	Test:       	TestMigration/mainnet-3309907/container
        	Messages:   	at instruction 71 (SYSCALL): failed native call: at instruction 1240 (THROW): unhandled exception: "pending vote detected"
```

**Comment by cthulhu-rider** [comment]
I'll add ballot age check to all tests.

**Comment by roman-khimov** [comment]
I had expected at least a single _complete_ successful run for mainnet. It probably doesn't the worth the trouble now, this code will never be executed again.
