### ISSUE TITLE
nns: Confusing type system of the contract

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#335]
https://pkg.go.dev/github.com/nspcc-dev/neofs-contract@v0.17.0/nns

I'm slightly confused by the contract API. We deal with
* `name string` - domain name
* `tokenID []byte` - domain name too (???)

If both of these elements are about the same entity, then I'd expect uniformity in method parameters.

I suppose this came from docs

> the domain name itself is your NFT

## Possible solution
Replace `tokenID []byte` with `name string` everywhere and don't forget about backwards.

**Comment by roman-khimov** [comment]
`tokenID` is used in NEP-11-compliant APIs, I guess, so it's a feature.

**Comment by roman-khimov** [comment]
Can't be done.
