### ISSUE TITLE
Licence files does not pass Go licence policy

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#424]
https://pkg.go.dev/github.com/nspcc-dev/neofs-contract@v0.20.0/common

docs arent rendered due to this

**Comment by roman-khimov** [comment]
Previous attempt with c28214181aff6c9579d5b51a5154c7b1ea3a8f29 has failed, unfortunately.

**Comment by roman-khimov** [comment]
Let's try https://github.com/golang/go/issues/68650.
