### ISSUE TITLE
Migrate Urfave CLI onto V2

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neofs-contract#426]
## Is your feature request related to a problem? Please describe.
`./scripts/` uses an outdated Urfave CLI v1.

## Describe the solution you'd like
Update it to v2, see https://github.com/nspcc-dev/neo-go/issues/3097.

**Comment by roman-khimov** [comment]
BTW, these are scripts, so https://github.com/nspcc-dev/locode-db/issues/34 is an option too.

**Comment by roman-khimov** [comment]
Let's drop this CLI dependency.
