### ISSUE TITLE
Do not calculate container ID in container.Put method

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-contract#85]
In current implementation `Container` contract calculates container ID in `Put` method by itself. 

Contract doesn't return calculated ID, so the calculation is performed on two sides at once: the calling and the contract.

I propose to add explicit argument to `Put` call with container identifier in order to not have a binding of the contract code for the identifier format, which can be dictated by the application logic. It will also reduce the computational load from the contract

**Comment by realloc** [comment]
I suggest to stick with current in-contract ID calculation. Independent ID calculation is the additional guarantee of container structure correctness.

Ideally InnerRing would not modify the container structure, but only ensure its correctness and approve creation.

**Comment by realloc** [comment]
@alexvanin @cthulhu-rider I suggest closing this issue, as the current mechanism assures the correctness of the structure and let's the container creator to make sure he got onchain what he expected.
