### ISSUE TITLE
Cannot `make` because the types of variables in `config.yml` and codes do not match

### ISSUE THREAD

**Issue by Hecate2** [nspcc-dev/neofs-contract#93]
I made a commit at https://github.com/Hecate2/neofs-contract/commit/77783809f0113334c2e22b3e8157b6145b9803e5 to `make` all the contracts successfully. But I have not checked whether the `nef` bytecodes are truely correct

**Comment by alexvanin** [comment]
> But I have not checked whether the nef bytecodes are truely correct

`nef` is pretty much the same, because it is compile type check, that can be disabled with `--no-events` flag.
